### ISSUE TITLE
无法使用docker:stable-dind container作为plugin服务器

### ISSUE THREAD

**Issue by ginozhu** [WeBankPartners/wecube-platform#946]
**描述您遇到的bug**  
插件部署后无法在docker:stable-dind上启动
```log
2019-12-06 18:15:11.465  INFO 16 --- [0.0-8080-exec-2] c.w.w.c.service.PluginInstanceService    : bucketName=wecube-plugin-package-bucket, fileName=qcloud-resource-management/v1.0/wecube-plugins-qcloud.tar, tmpFilePath= /tmp/20191206181511465/wecube-plugins-qcloud.tar
2019-12-06 18:15:12.373  INFO 16 --- [0.0-8080-exec-2] c.w.w.c.service.PluginInstanceService    : scp from local:/tmp/20191206181511465/wecube-plugins-qcloud.tar to remote/opt/
2019-12-06 18:15:12.518  INFO 16 --- [0.0-8080-exec-2] c.webank.wecube.core.service.ScpService  : Connection is OK
2019-12-06 18:15:12.522  INFO 16 --- [0.0-8080-exec-2] c.webank.wecube.core.service.ScpService  : scp local file [/tmp/20191206181511465/wecube-plugins-qcloud.tar] to remote target directory [/opt/]
2019-12-06 18:15:13.893  INFO 16 --- [0.0-8080-exec-2] c.w.w.c.service.PluginInstanceService    : Run command: docker load -i /opt/wecube-plugins-qcloud.tar
2019-12-06 18:15:14.043 ERROR 16 --- [0.0-8080-exec-2] .w.c.s.c.s.i.PooledRemoteCommandExecutor : execution error

java.util.concurrent.ExecutionException: java.lang.Exception: exec failed with code 127
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_112]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_112]
	at com.webank.wecube.core.service.cmder.ssh2.impl.PooledRemoteCommandExecutor.execute(PooledRemoteCommandExecutor.java:37) ~[classes!/:1.0-SNAPSHOT]
	at com.webank.wecube.core.service.CommandService.runAtRemote(CommandService.java:52) [classes!/:1.0-SNAPSHOT]

...

2019-12-06 18:15:14.047  INFO 16 --- [0.0-8080-exec-2] c.w.wecube.core.service.CommandService   : result container ID is: null
2019-12-06 18:15:14.048 ERROR 16 --- [0.0-8080-exec-2] c.w.w.c.service.PluginInstanceService    : Run command [docker load -i /opt/wecube-plugins-qcloud.tar] meet error: null
2019-12-06 18:15:14.056 ERROR 16 --- [0.0-8080-exec-2] c.w.w.c.c.DefaultExceptionHandler        : Create plugin package instance failed. Error is Run remote command meet error: null
```

**注意到插件可以正常通过ssh协议部署到docker dind container当中，但是remote command 【docker load -i /opt/wecube-plugins-qcloud.tar】报错
此时登入container 手动执行docker load -i /opt/wecube-plugins-qcloud.tar 命令是可以完成的（sh或者bash）**

(docker dind container已配置sh/bash命令)

```sh
/ # docker load -i /opt/wecube-plugins-qcloud.tar
...
Loaded image: wecube-plugins-qcloud:b603fa7
```

**如何重现** 

1. 启动插件服务器为docker:stable-dind
docker run --rm -it --privileged -p 9022:22 docker:stable-dind
2. 启动后进入container安装openssh并配置
3. 更改wecube platform相关配置
4. 在wecube platform上传并选择docker-dind服务器启动wecube-qcloud-plugin插件

**预期行为** 

plugin部署在docker容器里的ssh remote command应当正确被执行

**截图**  

![image](https://user-images.githubusercontent.com/1817557/70316835-7c9b5f00-1857-11ea-99e3-106edc42c316.png)

**附加**

**Comment by haixinhuang** [comment]
你好，首先感谢你的使用。
这个问题我需要先了解一下这个ip（10.22.18.112）是container的ip吗？

**Comment by ginozhu** [comment]
> 你好，首先感谢你的使用。
> 这个问题我需要先了解一下这个ip（10.22.18.112）是container的ip吗？

是宿主IP，但是10.22.18.112:9022转发至container的22端口
platform上插件服务器配置成10.22.18.112:9022
可以看到日志里scp的命令成功但是docker load失败

特地说明一下，这里用的container是docker:stable-dind，所以container内部装有完整独立docker
主要为了用在CI/CD的自动化打包测试，所以使用了docker-in-docker的容器作为插件服务器

**Comment by ginozhu** [comment]
是wecube platform使用的ch.ethz.ssh2库的问题，ssh2库远程execCommand时的environment和正常ssh进去不一致

**Comment by gavin2lee** [comment]
@ginozhu 开发团队正在积极定位该问题的原因。很大原因确实和您说的一样，是ch.ethz.ssh2库执行ssh命令权限不够所导致，但仍需要进一步定位根因。
1）在问题没有解决前，为不影响您的使用，建议尝试下不是docker in docker的方式。（该方式下，开发团队后续需要做多些测试）
2）后续有计划替换ssh直接访问容器的方式，而采用docker SDK。建议保持关注。
3）在问题定位出来前，建议该issue reopen。

进一步进展，我们会及时在这个issue的comment渠道与您update，或者email到您。

**Comment by junchensz** [comment]
命令结束返回代码127是"无法找到命令", 原因是docker:stable-dind container中，docker 命令位于/usr/local/bin/docker, 但是使用ch.ethz.ssh2库执行命令(ch.ethz.ssh2.Session.execCommand)时, /usr/local/bin/路径并不会在环境变量PATH中。关于这个，"Ganymed SSH-2 for Java"官网FAQ有特别说明  (但是里面的解决方案对应stable-dind似乎并不起作用)
http://www.ganymed.ethz.ch/ssh2/FAQ.html#env

解决方案如下,
1. 最简单的临时解决方案，在docker:stable-dind container中，把docker命令link到/usr/bin/路径下.
2. 使用sh -l -c 来执行远程命令, 其中-l 命令参数会作为一个登陆的Shell来执行命令 (/usr/local/bin/会被加入到环境变量里面), 已经提交到了946_remote_cmd分支, 后续会进行相关测试.
3. 应该可以用ch.ethz.ssh2.Session的PTY和shell方法来调用远程方法，不过改动较大，而且引入了其他的复杂性，暂时先不考虑.
